language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-typeangular' ]; then cd .. && eval "mv $currentfolder generator-typeangular" && cd generator-typeangular; fi

